Add rule for running all bots cases in row

diff --git a/tester b/tester
--- a/tester
+++ b/tester
@@ -3,6 +3,22 @@
 OPTITRUST=$(dirname $0)
 CURRENT_PATH=$(realpath --relative-to=${OPTITRUST} $(pwd))
 
+if [ "$1" == "bots" ]; then
+  cd ${OPTITRUST}
+  for c in $(ls ./case_studies/bots/apac); do
+    if [ -d "./case_studies/bots/apac/${c}" ]; then
+      echo -n "Running ${c}..."
+      OCAMLRUNPARAM=b dune exec "bots_${c}" > "./case_studies/bots/apac/${c}/${c}.log" 2>&1
+      if [ "$?" -ne 0 ]; then
+        echo "Fail"
+      else
+        echo "Done"
+      fi
+    fi
+  done
+  exit 0
+fi
+
 ARGS=()
 
 # If file is in the /src folder, then target the last test
